# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ChildProductInput(BaseModel):
    """
    ChildProductInput
    """ # noqa: E501
    scrape_session_id: Annotated[str, Field(min_length=1, strict=True, max_length=36)] = Field(alias="scrapeSessionId")
    sku: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    parent_sku: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="parentSku")
    barcode: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    key: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    key_name: Annotated[str, Field(strict=True, max_length=255)] = Field(alias="keyName")
    brand: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    vendor: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    style: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    color: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    colorcode: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    title: Optional[StrictStr] = None
    material: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    size1: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    size2: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    available_date: Optional[datetime] = Field(default=None, alias="availableDate")
    cost: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    msrp: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    map_price: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, alias="mapPrice")
    is_closeout: Optional[StrictBool] = Field(default=None, alias="isCloseout")
    images: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    metafields: Optional[StrictStr] = None
    data: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["scrapeSessionId", "sku", "parentSku", "barcode", "key", "keyName", "brand", "vendor", "style", "color", "colorcode", "title", "material", "size1", "size2", "availableDate", "cost", "msrp", "mapPrice", "isCloseout", "images", "url", "metafields", "data"]

    @field_validator('key_name')
    def key_name_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['sku', 'gtin', 'vendorsku']):
            raise ValueError("must be one of enum values ('sku', 'gtin', 'vendorsku')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChildProductInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sku (nullable) is None
        # and model_fields_set contains the field
        if self.sku is None and "sku" in self.model_fields_set:
            _dict['sku'] = None

        # set to None if parent_sku (nullable) is None
        # and model_fields_set contains the field
        if self.parent_sku is None and "parent_sku" in self.model_fields_set:
            _dict['parentSku'] = None

        # set to None if barcode (nullable) is None
        # and model_fields_set contains the field
        if self.barcode is None and "barcode" in self.model_fields_set:
            _dict['barcode'] = None

        # set to None if brand (nullable) is None
        # and model_fields_set contains the field
        if self.brand is None and "brand" in self.model_fields_set:
            _dict['brand'] = None

        # set to None if vendor (nullable) is None
        # and model_fields_set contains the field
        if self.vendor is None and "vendor" in self.model_fields_set:
            _dict['vendor'] = None

        # set to None if style (nullable) is None
        # and model_fields_set contains the field
        if self.style is None and "style" in self.model_fields_set:
            _dict['style'] = None

        # set to None if color (nullable) is None
        # and model_fields_set contains the field
        if self.color is None and "color" in self.model_fields_set:
            _dict['color'] = None

        # set to None if colorcode (nullable) is None
        # and model_fields_set contains the field
        if self.colorcode is None and "colorcode" in self.model_fields_set:
            _dict['colorcode'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if material (nullable) is None
        # and model_fields_set contains the field
        if self.material is None and "material" in self.model_fields_set:
            _dict['material'] = None

        # set to None if size1 (nullable) is None
        # and model_fields_set contains the field
        if self.size1 is None and "size1" in self.model_fields_set:
            _dict['size1'] = None

        # set to None if size2 (nullable) is None
        # and model_fields_set contains the field
        if self.size2 is None and "size2" in self.model_fields_set:
            _dict['size2'] = None

        # set to None if available_date (nullable) is None
        # and model_fields_set contains the field
        if self.available_date is None and "available_date" in self.model_fields_set:
            _dict['availableDate'] = None

        # set to None if cost (nullable) is None
        # and model_fields_set contains the field
        if self.cost is None and "cost" in self.model_fields_set:
            _dict['cost'] = None

        # set to None if msrp (nullable) is None
        # and model_fields_set contains the field
        if self.msrp is None and "msrp" in self.model_fields_set:
            _dict['msrp'] = None

        # set to None if map_price (nullable) is None
        # and model_fields_set contains the field
        if self.map_price is None and "map_price" in self.model_fields_set:
            _dict['mapPrice'] = None

        # set to None if images (nullable) is None
        # and model_fields_set contains the field
        if self.images is None and "images" in self.model_fields_set:
            _dict['images'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if metafields (nullable) is None
        # and model_fields_set contains the field
        if self.metafields is None and "metafields" in self.model_fields_set:
            _dict['metafields'] = None

        # set to None if data (nullable) is None
        # and model_fields_set contains the field
        if self.data is None and "data" in self.model_fields_set:
            _dict['data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChildProductInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scrapeSessionId": obj.get("scrapeSessionId"),
            "sku": obj.get("sku"),
            "parentSku": obj.get("parentSku"),
            "barcode": obj.get("barcode"),
            "key": obj.get("key"),
            "keyName": obj.get("keyName"),
            "brand": obj.get("brand"),
            "vendor": obj.get("vendor"),
            "style": obj.get("style"),
            "color": obj.get("color"),
            "colorcode": obj.get("colorcode"),
            "title": obj.get("title"),
            "material": obj.get("material"),
            "size1": obj.get("size1"),
            "size2": obj.get("size2"),
            "availableDate": obj.get("availableDate"),
            "cost": obj.get("cost"),
            "msrp": obj.get("msrp"),
            "mapPrice": obj.get("mapPrice"),
            "isCloseout": obj.get("isCloseout"),
            "images": obj.get("images"),
            "url": obj.get("url"),
            "metafields": obj.get("metafields"),
            "data": obj.get("data")
        })
        return _obj


