# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CompleteScrapeRequest(BaseModel):
    """
    CompleteScrapeRequest
    """ # noqa: E501
    success_count: Annotated[int, Field(strict=True, ge=0)] = Field(alias="successCount")
    error_count: Annotated[int, Field(strict=True, ge=0)] = Field(alias="errorCount")
    warning_count: Annotated[int, Field(strict=True, ge=0)] = Field(alias="warningCount")
    message: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = None
    status_code: StrictStr = Field(alias="statusCode")
    __properties: ClassVar[List[str]] = ["successCount", "errorCount", "warningCount", "message", "statusCode"]

    @field_validator('status_code')
    def status_code_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SUCCESS', 'FAILED', 'KILL_REQUEST']):
            raise ValueError("must be one of enum values ('SUCCESS', 'FAILED', 'KILL_REQUEST')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CompleteScrapeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CompleteScrapeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "successCount": obj.get("successCount"),
            "errorCount": obj.get("errorCount"),
            "warningCount": obj.get("warningCount"),
            "message": obj.get("message"),
            "statusCode": obj.get("statusCode")
        })
        return _obj


