# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from scrapehub_client.models.child_product_input import ChildProductInput
from scrapehub_client.models.free_data_input import FreeDataInput
from scrapehub_client.models.parent_product_input import ParentProductInput
from scrapehub_client.models.record_type import RecordType
from typing import Optional, Set
from typing_extensions import Self

class DataRecord(BaseModel):
    """
    DataRecord
    """ # noqa: E501
    record_type: RecordType = Field(alias="recordType")
    version: StrictStr
    child_product: Optional[ChildProductInput] = Field(default=None, alias="childProduct")
    parent_product: Optional[ParentProductInput] = Field(default=None, alias="parentProduct")
    free_data: Optional[FreeDataInput] = Field(default=None, alias="freeData")
    __properties: ClassVar[List[str]] = ["recordType", "version", "childProduct", "parentProduct", "freeData"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of child_product
        if self.child_product:
            _dict['childProduct'] = self.child_product.to_dict()
        # override the default output from pydantic by calling `to_dict()` of parent_product
        if self.parent_product:
            _dict['parentProduct'] = self.parent_product.to_dict()
        # override the default output from pydantic by calling `to_dict()` of free_data
        if self.free_data:
            _dict['freeData'] = self.free_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recordType": obj.get("recordType"),
            "version": obj.get("version"),
            "childProduct": ChildProductInput.from_dict(obj["childProduct"]) if obj.get("childProduct") is not None else None,
            "parentProduct": ParentProductInput.from_dict(obj["parentProduct"]) if obj.get("parentProduct") is not None else None,
            "freeData": FreeDataInput.from_dict(obj["freeData"]) if obj.get("freeData") is not None else None
        })
        return _obj


