# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ParentProductInput(BaseModel):
    """
    ParentProductInput
    """ # noqa: E501
    scrape_session_id: Annotated[str, Field(min_length=1, strict=True, max_length=36)] = Field(alias="scrapeSessionId")
    parent_sku: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(alias="parentSku")
    brand: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    vendor: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    style: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    model: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    title: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    description: Optional[StrictStr] = None
    bullets: Optional[StrictStr] = None
    category: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    sub_category: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="subCategory")
    department: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    season: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    images: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    metafields: Optional[StrictStr] = None
    data: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["scrapeSessionId", "parentSku", "brand", "vendor", "style", "model", "title", "description", "bullets", "category", "subCategory", "department", "season", "images", "url", "metafields", "data"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ParentProductInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if brand (nullable) is None
        # and model_fields_set contains the field
        if self.brand is None and "brand" in self.model_fields_set:
            _dict['brand'] = None

        # set to None if vendor (nullable) is None
        # and model_fields_set contains the field
        if self.vendor is None and "vendor" in self.model_fields_set:
            _dict['vendor'] = None

        # set to None if style (nullable) is None
        # and model_fields_set contains the field
        if self.style is None and "style" in self.model_fields_set:
            _dict['style'] = None

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if bullets (nullable) is None
        # and model_fields_set contains the field
        if self.bullets is None and "bullets" in self.model_fields_set:
            _dict['bullets'] = None

        # set to None if category (nullable) is None
        # and model_fields_set contains the field
        if self.category is None and "category" in self.model_fields_set:
            _dict['category'] = None

        # set to None if sub_category (nullable) is None
        # and model_fields_set contains the field
        if self.sub_category is None and "sub_category" in self.model_fields_set:
            _dict['subCategory'] = None

        # set to None if department (nullable) is None
        # and model_fields_set contains the field
        if self.department is None and "department" in self.model_fields_set:
            _dict['department'] = None

        # set to None if season (nullable) is None
        # and model_fields_set contains the field
        if self.season is None and "season" in self.model_fields_set:
            _dict['season'] = None

        # set to None if images (nullable) is None
        # and model_fields_set contains the field
        if self.images is None and "images" in self.model_fields_set:
            _dict['images'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if metafields (nullable) is None
        # and model_fields_set contains the field
        if self.metafields is None and "metafields" in self.model_fields_set:
            _dict['metafields'] = None

        # set to None if data (nullable) is None
        # and model_fields_set contains the field
        if self.data is None and "data" in self.model_fields_set:
            _dict['data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ParentProductInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "scrapeSessionId": obj.get("scrapeSessionId"),
            "parentSku": obj.get("parentSku"),
            "brand": obj.get("brand"),
            "vendor": obj.get("vendor"),
            "style": obj.get("style"),
            "model": obj.get("model"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "bullets": obj.get("bullets"),
            "category": obj.get("category"),
            "subCategory": obj.get("subCategory"),
            "department": obj.get("department"),
            "season": obj.get("season"),
            "images": obj.get("images"),
            "url": obj.get("url"),
            "metafields": obj.get("metafields"),
            "data": obj.get("data")
        })
        return _obj


