# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.scraper_profile_response_data import ScraperProfileResponseData

class TestScraperProfileResponseData(unittest.TestCase):
    """ScraperProfileResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScraperProfileResponseData:
        """Test ScraperProfileResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScraperProfileResponseData`
        """
        model = ScraperProfileResponseData()
        if include_optional:
            return ScraperProfileResponseData(
                publish_inventory = True,
                cron = '',
                assigned_to = [
                    ''
                    ],
                settings = {
                    'key' : null
                    },
                password = '',
                username = '',
                notes = '',
                disabled_date = '',
                is_disabled = True,
                type = '',
                description = '',
                name = ''
            )
        else:
            return ScraperProfileResponseData(
                publish_inventory = True,
                is_disabled = True,
                type = '',
                name = '',
        )
        """

    def testScraperProfileResponseData(self):
        """Test ScraperProfileResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
