# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.scraper_message_response import ScraperMessageResponse

class TestScraperMessageResponse(unittest.TestCase):
    """ScraperMessageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScraperMessageResponse:
        """Test ScraperMessageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScraperMessageResponse`
        """
        model = ScraperMessageResponse()
        if include_optional:
            return ScraperMessageResponse(
                id = '',
                scraper_id = '',
                scraper_name = '',
                message_type = 'KILL_REQUEST',
                message = '',
                created_at = '',
                expires_at = ''
            )
        else:
            return ScraperMessageResponse(
                id = '',
                scraper_id = '',
                scraper_name = '',
                message_type = 'KILL_REQUEST',
                created_at = '',
        )
        """

    def testScraperMessageResponse(self):
        """Test ScraperMessageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
