# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.update_type import UpdateType

class TestUpdateType(unittest.TestCase):
    """UpdateType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateType(self):
        """Test UpdateType"""
        # inst = UpdateType()

if __name__ == '__main__':
    unittest.main()
