# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.start_scrape200_response import StartScrape200Response

class TestStartScrape200Response(unittest.TestCase):
    """StartScrape200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartScrape200Response:
        """Test StartScrape200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartScrape200Response`
        """
        model = StartScrape200Response()
        if include_optional:
            return StartScrape200Response(
                success = True,
                message = '',
                session_id = '',
                code = '',
                trace_id = ''
            )
        else:
            return StartScrape200Response(
                success = True,
                message = '',
                session_id = '',
                code = '',
        )
        """

    def testStartScrape200Response(self):
        """Test StartScrape200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
