# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.record_data_request import RecordDataRequest

class TestRecordDataRequest(unittest.TestCase):
    """RecordDataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordDataRequest:
        """Test RecordDataRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordDataRequest`
        """
        model = RecordDataRequest()
        if include_optional:
            return RecordDataRequest(
                session_id = '',
                records = [
                    scrapehub_client.models.data_record.DataRecord(
                        record_type = 'CHILD_PRODUCT', 
                        version = '', 
                        child_product = scrapehub_client.models.child_product_input.ChildProductInput(
                            scrape_session_id = '0', 
                            sku = '', 
                            parent_sku = '', 
                            barcode = '', 
                            key = '0', 
                            key_name = 'sku', 
                            brand = '', 
                            vendor = '', 
                            style = '', 
                            color = '', 
                            colorcode = '', 
                            title = '', 
                            material = '', 
                            size1 = '', 
                            size2 = '', 
                            available_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            cost = 0, 
                            msrp = 0, 
                            map_price = 0, 
                            is_closeout = True, 
                            images = '', 
                            url = '', 
                            metafields = '', 
                            data = '', ), 
                        parent_product = scrapehub_client.models.parent_product_input.ParentProductInput(
                            scrape_session_id = '0', 
                            parent_sku = '0', 
                            brand = '', 
                            vendor = '', 
                            style = '', 
                            model = '', 
                            title = '', 
                            description = '', 
                            bullets = '', 
                            category = '', 
                            sub_category = '', 
                            department = '', 
                            season = '', 
                            images = '', 
                            url = '', 
                            metafields = '', 
                            data = '', ), 
                        free_data = scrapehub_client.models.free_data_input.FreeDataInput(
                            scrape_session_id = '0', 
                            key = '0', 
                            key_name = '', 
                            metafields = '', 
                            data = '', ), )
                    ]
            )
        else:
            return RecordDataRequest(
                session_id = '',
                records = [
                    scrapehub_client.models.data_record.DataRecord(
                        record_type = 'CHILD_PRODUCT', 
                        version = '', 
                        child_product = scrapehub_client.models.child_product_input.ChildProductInput(
                            scrape_session_id = '0', 
                            sku = '', 
                            parent_sku = '', 
                            barcode = '', 
                            key = '0', 
                            key_name = 'sku', 
                            brand = '', 
                            vendor = '', 
                            style = '', 
                            color = '', 
                            colorcode = '', 
                            title = '', 
                            material = '', 
                            size1 = '', 
                            size2 = '', 
                            available_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            cost = 0, 
                            msrp = 0, 
                            map_price = 0, 
                            is_closeout = True, 
                            images = '', 
                            url = '', 
                            metafields = '', 
                            data = '', ), 
                        parent_product = scrapehub_client.models.parent_product_input.ParentProductInput(
                            scrape_session_id = '0', 
                            parent_sku = '0', 
                            brand = '', 
                            vendor = '', 
                            style = '', 
                            model = '', 
                            title = '', 
                            description = '', 
                            bullets = '', 
                            category = '', 
                            sub_category = '', 
                            department = '', 
                            season = '', 
                            images = '', 
                            url = '', 
                            metafields = '', 
                            data = '', ), 
                        free_data = scrapehub_client.models.free_data_input.FreeDataInput(
                            scrape_session_id = '0', 
                            key = '0', 
                            key_name = '', 
                            metafields = '', 
                            data = '', ), )
                    ],
        )
        """

    def testRecordDataRequest(self):
        """Test RecordDataRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
