# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.parent_product_input import ParentProductInput

class TestParentProductInput(unittest.TestCase):
    """ParentProductInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ParentProductInput:
        """Test ParentProductInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ParentProductInput`
        """
        model = ParentProductInput()
        if include_optional:
            return ParentProductInput(
                scrape_session_id = '0',
                parent_sku = '0',
                brand = '',
                vendor = '',
                style = '',
                model = '',
                title = '',
                description = '',
                bullets = '',
                category = '',
                sub_category = '',
                department = '',
                season = '',
                images = '',
                url = '',
                metafields = '',
                data = ''
            )
        else:
            return ParentProductInput(
                scrape_session_id = '0',
                parent_sku = '0',
        )
        """

    def testParentProductInput(self):
        """Test ParentProductInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
