# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.complete_scrape_response import CompleteScrapeResponse

class TestCompleteScrapeResponse(unittest.TestCase):
    """CompleteScrapeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompleteScrapeResponse:
        """Test CompleteScrapeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompleteScrapeResponse`
        """
        model = CompleteScrapeResponse()
        if include_optional:
            return CompleteScrapeResponse(
                success = True,
                message = '',
                session_id = ''
            )
        else:
            return CompleteScrapeResponse(
                success = True,
                session_id = '',
        )
        """

    def testCompleteScrapeResponse(self):
        """Test CompleteScrapeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
