# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.record_error_request import RecordErrorRequest

class TestRecordErrorRequest(unittest.TestCase):
    """RecordErrorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordErrorRequest:
        """Test RecordErrorRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordErrorRequest`
        """
        model = RecordErrorRequest()
        if include_optional:
            return RecordErrorRequest(
                error = scrapehub_client.models.pick_scrape_session_error_log/exclude_keyof_scrape_session_error_log/id_or_created_at__.Pick_ScrapeSessionErrorLog.Exclude_keyofScrapeSessionErrorLog.id-or-createdAt__(
                    session_id = '', 
                    error_type = '', 
                    severity = '', 
                    message = '', 
                    stack_trace = '', 
                    details = '', 
                    context = '', )
            )
        else:
            return RecordErrorRequest(
                error = scrapehub_client.models.pick_scrape_session_error_log/exclude_keyof_scrape_session_error_log/id_or_created_at__.Pick_ScrapeSessionErrorLog.Exclude_keyofScrapeSessionErrorLog.id-or-createdAt__(
                    session_id = '', 
                    error_type = '', 
                    severity = '', 
                    message = '', 
                    stack_trace = '', 
                    details = '', 
                    context = '', ),
        )
        """

    def testRecordErrorRequest(self):
        """Test RecordErrorRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
