# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.scraper_profile_response import ScraperProfileResponse

class TestScraperProfileResponse(unittest.TestCase):
    """ScraperProfileResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScraperProfileResponse:
        """Test ScraperProfileResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScraperProfileResponse`
        """
        model = ScraperProfileResponse()
        if include_optional:
            return ScraperProfileResponse(
                success = True,
                message = '',
                data = scrapehub_client.models.scraper_profile_response_data.ScraperProfileResponse_data(
                    publish_inventory = True, 
                    cron = '', 
                    assigned_to = [
                        ''
                        ], 
                    settings = {
                        'key' : null
                        }, 
                    password = '', 
                    username = '', 
                    notes = '', 
                    disabled_date = '', 
                    is_disabled = True, 
                    type = '', 
                    description = '', 
                    name = '', )
            )
        else:
            return ScraperProfileResponse(
                success = True,
                data = scrapehub_client.models.scraper_profile_response_data.ScraperProfileResponse_data(
                    publish_inventory = True, 
                    cron = '', 
                    assigned_to = [
                        ''
                        ], 
                    settings = {
                        'key' : null
                        }, 
                    password = '', 
                    username = '', 
                    notes = '', 
                    disabled_date = '', 
                    is_disabled = True, 
                    type = '', 
                    description = '', 
                    name = '', ),
        )
        """

    def testScraperProfileResponse(self):
        """Test ScraperProfileResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
