# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.user_settings_response import UserSettingsResponse

class TestUserSettingsResponse(unittest.TestCase):
    """UserSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSettingsResponse:
        """Test UserSettingsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSettingsResponse`
        """
        model = UserSettingsResponse()
        if include_optional:
            return UserSettingsResponse(
                success = True,
                message = '',
                data = scrapehub_client.models.user_settings_response_data.UserSettingsResponse_data(
                    scraper_assignments = [
                        ''
                        ], 
                    roles = [
                        ''
                        ], 
                    settings = {
                        'key' : null
                        }, 
                    fullname = '', 
                    email = '', 
                    username = '', )
            )
        else:
            return UserSettingsResponse(
                success = True,
                data = scrapehub_client.models.user_settings_response_data.UserSettingsResponse_data(
                    scraper_assignments = [
                        ''
                        ], 
                    roles = [
                        ''
                        ], 
                    settings = {
                        'key' : null
                        }, 
                    fullname = '', 
                    email = '', 
                    username = '', ),
        )
        """

    def testUserSettingsResponse(self):
        """Test UserSettingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
