# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.ack_message_request import AckMessageRequest

class TestAckMessageRequest(unittest.TestCase):
    """AckMessageRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AckMessageRequest:
        """Test AckMessageRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AckMessageRequest`
        """
        model = AckMessageRequest()
        if include_optional:
            return AckMessageRequest(
                message_id = '0'
            )
        else:
            return AckMessageRequest(
                message_id = '0',
        )
        """

    def testAckMessageRequest(self):
        """Test AckMessageRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
