# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.api.scraping_operations_api import ScrapingOperationsApi


class TestScrapingOperationsApi(unittest.TestCase):
    """ScrapingOperationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScrapingOperationsApi()

    def tearDown(self) -> None:
        pass

    def test_complete_scrape(self) -> None:
        """Test case for complete_scrape

        """
        pass

    def test_record_data(self) -> None:
        """Test case for record_data

        """
        pass

    def test_record_error(self) -> None:
        """Test case for record_error

        """
        pass

    def test_start_scrape(self) -> None:
        """Test case for start_scrape

        """
        pass

    def test_update_progress(self) -> None:
        """Test case for update_progress

        """
        pass


if __name__ == '__main__':
    unittest.main()
