# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.child_product_input import ChildProductInput

class TestChildProductInput(unittest.TestCase):
    """ChildProductInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChildProductInput:
        """Test ChildProductInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChildProductInput`
        """
        model = ChildProductInput()
        if include_optional:
            return ChildProductInput(
                scrape_session_id = '0',
                sku = '',
                parent_sku = '',
                barcode = '',
                key = '0',
                key_name = 'sku',
                brand = '',
                vendor = '',
                style = '',
                color = '',
                colorcode = '',
                title = '',
                material = '',
                size1 = '',
                size2 = '',
                available_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cost = 0,
                msrp = 0,
                map_price = 0,
                is_closeout = True,
                images = '',
                url = '',
                metafields = '',
                data = ''
            )
        else:
            return ChildProductInput(
                scrape_session_id = '0',
                key = '0',
                key_name = 'sku',
        )
        """

    def testChildProductInput(self):
        """Test ChildProductInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
