# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.api.scrape_hub_api_api import ScrapeHubAPIApi


class TestScrapeHubAPIApi(unittest.TestCase):
    """ScrapeHubAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScrapeHubAPIApi()

    def tearDown(self) -> None:
        pass

    def test_get_scraper_profile(self) -> None:
        """Test case for get_scraper_profile

        """
        pass

    def test_get_user_settings(self) -> None:
        """Test case for get_user_settings

        """
        pass

    def test_get_version(self) -> None:
        """Test case for get_version

        """
        pass


if __name__ == '__main__':
    unittest.main()
