# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.update_progress_request import UpdateProgressRequest

class TestUpdateProgressRequest(unittest.TestCase):
    """UpdateProgressRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateProgressRequest:
        """Test UpdateProgressRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateProgressRequest`
        """
        model = UpdateProgressRequest()
        if include_optional:
            return UpdateProgressRequest(
                success_count = 0,
                error_count = 0,
                warning_count = 0,
                message = '0',
                total_count = 0,
                update_type = 'progress'
            )
        else:
            return UpdateProgressRequest(
                success_count = 0,
                error_count = 0,
                warning_count = 0,
                message = '0',
                total_count = 0,
                update_type = 'progress',
        )
        """

    def testUpdateProgressRequest(self):
        """Test UpdateProgressRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
