# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.get_user_settings200_response import GetUserSettings200Response

class TestGetUserSettings200Response(unittest.TestCase):
    """GetUserSettings200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserSettings200Response:
        """Test GetUserSettings200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserSettings200Response`
        """
        model = GetUserSettings200Response()
        if include_optional:
            return GetUserSettings200Response(
                success = True,
                message = '',
                data = scrapehub_client.models.user_settings_response_data.UserSettingsResponse_data(
                    scraper_assignments = [
                        ''
                        ], 
                    roles = [
                        ''
                        ], 
                    settings = {
                        'key' : null
                        }, 
                    fullname = '', 
                    email = '', 
                    username = '', ),
                code = '',
                trace_id = ''
            )
        else:
            return GetUserSettings200Response(
                success = True,
                message = '',
                data = scrapehub_client.models.user_settings_response_data.UserSettingsResponse_data(
                    scraper_assignments = [
                        ''
                        ], 
                    roles = [
                        ''
                        ], 
                    settings = {
                        'key' : null
                        }, 
                    fullname = '', 
                    email = '', 
                    username = '', ),
                code = '',
        )
        """

    def testGetUserSettings200Response(self):
        """Test GetUserSettings200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
