# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.update_progress200_response import UpdateProgress200Response

class TestUpdateProgress200Response(unittest.TestCase):
    """UpdateProgress200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateProgress200Response:
        """Test UpdateProgress200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateProgress200Response`
        """
        model = UpdateProgress200Response()
        if include_optional:
            return UpdateProgress200Response(
                success = True,
                message = '',
                session_id = '',
                scrape_session_update_id = '',
                code = '',
                trace_id = ''
            )
        else:
            return UpdateProgress200Response(
                success = True,
                message = '',
                session_id = '',
                code = '',
        )
        """

    def testUpdateProgress200Response(self):
        """Test UpdateProgress200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
