# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.record_error_response import RecordErrorResponse

class TestRecordErrorResponse(unittest.TestCase):
    """RecordErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordErrorResponse:
        """Test RecordErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordErrorResponse`
        """
        model = RecordErrorResponse()
        if include_optional:
            return RecordErrorResponse(
                success = True,
                message = '',
                data = scrapehub_client.models.default_selection_prisma/_36_scrape_session_error_log_payload_.DefaultSelection_Prisma._36_ScrapeSessionErrorLogPayload_(
                    context = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    details = '', 
                    stack_trace = '', 
                    message = '', 
                    severity = '', 
                    error_type = '', 
                    session_id = '', 
                    id = 1.337, )
            )
        else:
            return RecordErrorResponse(
                success = True,
                data = scrapehub_client.models.default_selection_prisma/_36_scrape_session_error_log_payload_.DefaultSelection_Prisma._36_ScrapeSessionErrorLogPayload_(
                    context = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    details = '', 
                    stack_trace = '', 
                    message = '', 
                    severity = '', 
                    error_type = '', 
                    session_id = '', 
                    id = 1.337, ),
        )
        """

    def testRecordErrorResponse(self):
        """Test RecordErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
