# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.start_scrape_response import StartScrapeResponse

class TestStartScrapeResponse(unittest.TestCase):
    """StartScrapeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartScrapeResponse:
        """Test StartScrapeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartScrapeResponse`
        """
        model = StartScrapeResponse()
        if include_optional:
            return StartScrapeResponse(
                success = True,
                message = '',
                session_id = ''
            )
        else:
            return StartScrapeResponse(
                success = True,
                session_id = '',
        )
        """

    def testStartScrapeResponse(self):
        """Test StartScrapeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
