# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.send_message_response import SendMessageResponse

class TestSendMessageResponse(unittest.TestCase):
    """SendMessageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendMessageResponse:
        """Test SendMessageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendMessageResponse`
        """
        model = SendMessageResponse()
        if include_optional:
            return SendMessageResponse(
                success = True,
                message = '',
                message_id = ''
            )
        else:
            return SendMessageResponse(
                success = True,
                message_id = '',
        )
        """

    def testSendMessageResponse(self):
        """Test SendMessageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
