# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.default_selection_prisma36_scrape_session_error_log_payload import DefaultSelectionPrisma36ScrapeSessionErrorLogPayload

class TestDefaultSelectionPrisma36ScrapeSessionErrorLogPayload(unittest.TestCase):
    """DefaultSelectionPrisma36ScrapeSessionErrorLogPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DefaultSelectionPrisma36ScrapeSessionErrorLogPayload:
        """Test DefaultSelectionPrisma36ScrapeSessionErrorLogPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DefaultSelectionPrisma36ScrapeSessionErrorLogPayload`
        """
        model = DefaultSelectionPrisma36ScrapeSessionErrorLogPayload()
        if include_optional:
            return DefaultSelectionPrisma36ScrapeSessionErrorLogPayload(
                context = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                details = '',
                stack_trace = '',
                message = '',
                severity = '',
                error_type = '',
                session_id = '',
                id = 1.337
            )
        else:
            return DefaultSelectionPrisma36ScrapeSessionErrorLogPayload(
                context = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                details = '',
                stack_trace = '',
                message = '',
                severity = '',
                error_type = '',
                session_id = '',
                id = 1.337,
        )
        """

    def testDefaultSelectionPrisma36ScrapeSessionErrorLogPayload(self):
        """Test DefaultSelectionPrisma36ScrapeSessionErrorLogPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
