# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.pick_scrape_session_error_log_exclude_keyof_scrape_session_error_log_id_or_created_at import PickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt

class TestPickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt(unittest.TestCase):
    """PickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt:
        """Test PickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt`
        """
        model = PickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt()
        if include_optional:
            return PickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt(
                session_id = '',
                error_type = '',
                severity = '',
                message = '',
                stack_trace = '',
                details = '',
                context = ''
            )
        else:
            return PickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt(
                session_id = '',
                error_type = '',
                severity = '',
                message = '',
                stack_trace = '',
                details = '',
                context = '',
        )
        """

    def testPickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt(self):
        """Test PickScrapeSessionErrorLogExcludeKeyofScrapeSessionErrorLogIdOrCreatedAt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
