# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.api.scrape_hub_api_messaging_api import ScrapeHubAPIMessagingApi


class TestScrapeHubAPIMessagingApi(unittest.TestCase):
    """ScrapeHubAPIMessagingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScrapeHubAPIMessagingApi()

    def tearDown(self) -> None:
        pass

    def test_ack_message(self) -> None:
        """Test case for ack_message

        """
        pass

    def test_get_messages(self) -> None:
        """Test case for get_messages

        """
        pass

    def test_send_message(self) -> None:
        """Test case for send_message

        """
        pass


if __name__ == '__main__':
    unittest.main()
