# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.free_data_input import FreeDataInput

class TestFreeDataInput(unittest.TestCase):
    """FreeDataInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FreeDataInput:
        """Test FreeDataInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FreeDataInput`
        """
        model = FreeDataInput()
        if include_optional:
            return FreeDataInput(
                scrape_session_id = '0',
                key = '0',
                key_name = '',
                metafields = '',
                data = ''
            )
        else:
            return FreeDataInput(
                scrape_session_id = '0',
                key = '0',
        )
        """

    def testFreeDataInput(self):
        """Test FreeDataInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
