# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.ack_message_response import AckMessageResponse

class TestAckMessageResponse(unittest.TestCase):
    """AckMessageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AckMessageResponse:
        """Test AckMessageResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AckMessageResponse`
        """
        model = AckMessageResponse()
        if include_optional:
            return AckMessageResponse(
                success = True,
                message = '',
                acknowledged_at = ''
            )
        else:
            return AckMessageResponse(
                success = True,
                acknowledged_at = '',
        )
        """

    def testAckMessageResponse(self):
        """Test AckMessageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
