# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.ack_message200_response import AckMessage200Response

class TestAckMessage200Response(unittest.TestCase):
    """AckMessage200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AckMessage200Response:
        """Test AckMessage200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AckMessage200Response`
        """
        model = AckMessage200Response()
        if include_optional:
            return AckMessage200Response(
                success = True,
                message = '',
                acknowledged_at = '',
                code = '',
                trace_id = ''
            )
        else:
            return AckMessage200Response(
                success = True,
                message = '',
                acknowledged_at = '',
                code = '',
        )
        """

    def testAckMessage200Response(self):
        """Test AckMessage200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
