# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.record_data200_response import RecordData200Response

class TestRecordData200Response(unittest.TestCase):
    """RecordData200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecordData200Response:
        """Test RecordData200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecordData200Response`
        """
        model = RecordData200Response()
        if include_optional:
            return RecordData200Response(
                success = True,
                message = '',
                records_processed = 1.337,
                code = '',
                trace_id = ''
            )
        else:
            return RecordData200Response(
                success = True,
                message = '',
                records_processed = 1.337,
                code = '',
        )
        """

    def testRecordData200Response(self):
        """Test RecordData200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
