# coding: utf-8

"""
    ScrapeHub API

    API for managing web scrapers

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapehub_client.models.complete_scrape_request import CompleteScrapeRequest

class TestCompleteScrapeRequest(unittest.TestCase):
    """CompleteScrapeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompleteScrapeRequest:
        """Test CompleteScrapeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompleteScrapeRequest`
        """
        model = CompleteScrapeRequest()
        if include_optional:
            return CompleteScrapeRequest(
                success_count = 0,
                error_count = 0,
                warning_count = 0,
                message = '',
                status_code = 'SUCCESS'
            )
        else:
            return CompleteScrapeRequest(
                success_count = 0,
                error_count = 0,
                warning_count = 0,
                status_code = 'SUCCESS',
        )
        """

    def testCompleteScrapeRequest(self):
        """Test CompleteScrapeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
